### ISSUE TITLE
What versions of OpenStack are supported?

### ISSUE THREAD

**Issue by ftcjeff** [openbaton/openstack-plugin#6]
Hi, I've just installed OpenStack / devstack on an Ubuntu 16.04 VM and it's running properly. I can access it using the CLI as well as the dashboard.  I can also access it from my VM that's hosting OpenBaton via curl:

pops [~] ➟ curl -X GET http://<ipaddr>/identity/v3
{"version": {"status": "stable", "updated": "2016-10-06T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v3+json"}], "id": "v3.7", "links": [{"href": "http://16.78.179.9/identity/v3/", "rel": "self"}]}}

But when I try to register a PoP against this VIM I get:

ERROR: HTTP status: 422 response data : {"code":"Bad Request","message":"Not listed Images successfully of VimInstance pops-openstack-vm-vim. Caused by: org.openbaton.exceptions.VimDriverException: {\"error\": {\"message\": \"The resource could not be found.\", \"code\": 404, \"title\": \"Not Found\"}}"}

Sure enough, when I curl that URI I get:

pops [~] ➟ curl -X GET http://<ipaddr>/identity/v3/tokens
{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}

Here's the relevant bits from the log: https://gist.github.com/ftcjeff/0621ce08c7c1c4295b125dc48f66190b

So my question is, what versions of OpenStack should I be able to use with OpenBaton? Is there something obvious that I'm doing wrong with devstack? Thanks for any help or pointers!

**Comment by ftcjeff** [comment]
Ooooh. I figured it out. I forgot to show you my vim JSON config and noticed that I was using:

http://<ip>/identity 

as my authUrl. This is the URI that devstack spat out.  If I change that to:

http://<ip>:5000/v2.0

Then the OpenStack VIM is registered correctly!

**Comment by gc4rella** [comment]
OK! Great :-) ...I was just going to reply you that the plugin has been tested with Mitaka. We are currently working hard for launching release 3 next week, and we'll later on look into supporting Newton.

**Comment by gc4rella** [comment]
btw, the current plugin has some limitations in terms of networking, since it assumes that networks (at least externals) are properly configured by you in advance. Therefore I suggest you to configure the networks you plan to use for your VNFs before launching the Network Service. Configure means adding private networks and attaching them to a router in case you plan to use floating IPs. Otherwise, we'll be happy to receive feedbacks on your experience, as we plan to rewrite the plugin in python pretty soon.

**Comment by ftcjeff** [comment]
Hey @gc4rella quick question - since I installed OpenStack via devstack, wouldn't that have set up the networks correctly?  How should I set them up if that's not correct already?  Thanks!
